kind: Service
apiVersion: v1
metadata:
  name: dicom-viewer-service
spec:
  selector:
    app: viewer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: null
      name: http
  type: ClusterIP