apiVersion: apps/v1
kind: Deployment
metadata:
  name: dicom-viewer-deployment
spec:
  selector:
    # Only select pods based on the 'app' label
    matchLabels:
      app: orthanc
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: orthanc
        public: "yes"
        netnolimit: "yes"
        tags.datadoghq.com/service: "orthanc"
        GEN3_GUPPY_VERSION
        GEN3_ENV_LABEL
        GEN3_DATE_LABEL
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - orthanc
              topologyKey: "kubernetes.io/hostname"
      automountServiceAccountToken: false
      containers:
        - name: viewer
          GEN3_ORTHANC_IMAGE|-image: quay.io/cdis/ohif-viewer
          # livenessProbe:
          #   httpGet:
          #     path: /_status
          #     port: 8080:80
          #   initialDelaySeconds: 30
          #   periodSeconds: 60
          #   timeoutSeconds: 30
          # readinessProbe:
          #   httpGet:
          #     path: /_status
          #     port: 8000
          ports:
          - containerPort: 8080:80
          env:
          - name: DD_TRACE_ENABLED
            valueFrom:
              configMapKeyRef:
                name: manifest-global
                key: dd_enabled
                optional: true
          - name: DD_ENV
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['tags.datadoghq.com/env']
          - name: DD_SERVICE
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['tags.datadoghq.com/service']
          - name: DD_VERSION
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['tags.datadoghq.com/version']
          - name: DD_LOGS_INJECTION
            value: "true"
          - name: DD_PROFILING_ENABLED
            value: "true"
          - name: DD_TRACE_SAMPLE_RATE
            value: "1"
          - name: DD_TRACE_AGENT_HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 0.5
              memory: 1024Mi
            limits:
              cpu: 1
              memory: 2400Mi  