apiVersion: apps/v1
kind: Deployment
metadata:
  name: viewer-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: viewer
  template:
    metadata:
      labels:
        app: viewer
    spec:
      containers:
      - name: viewer
        image: ohif/viewer
        ports:
        - containerPort: 80
        