apiVersion: apps/v1
kind: Deployment
metadata:
  name: orthanc-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orthanc
  template:
    metadata:
      labels:
        app: orthanc
    spec:
      containers:
      - name: orthanc
        image: osimis/orthanc
        ports:
        - containerPort: 80
        

