apiVersion: apps/v1
kind: Deployment
metadata:
  name: orthanc-deployment
spec:
  selector:
    # Only select pods based on the 'app' label
    matchLabels:
      app: orthanc
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: orthanc
        public: "yes"
        netnolimit: "yes"
        tags.datadoghq.com/service: "orthanc"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - orthanc
              topologyKey: "kubernetes.io/hostname"
      automountServiceAccountToken: false
      containers:
      - name: orthanc 
        GEN3_ORTHANC_IMAGE
        imagePullPolicy: Always
        resources:
            limits:
              cpu: 1
              memory: 2400Mi  
        ports:
        - containerPort: 8080:80
        env:
        - name: DD_TRACE_ENABLED
          valueFrom:
            configMapKeyRef:
               name: manifest-global
               key: dd_enabled
               optional: true
          
