kind: Service
apiVersion: v1
metadata:
  name: orthanc-service
spec:
  selector:
    app: orthanc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8042
      nodePort: null
      name: http
  type: ClusterIP
  
